# Generated by Django 4.0.6 on 2022-08-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
